// Product catalog (shared)
window.PRODUCTS = [
  { id:"sweet-pink-roses", name:"Sweet Pink Roses", price:1499, old:1799, category:"birthday", tag:"Bestseller",
    img:"assets/p-birthday.jpg",
    short:"A romantic blush bouquet of 18 garden roses & gerberas.",
    desc:"Hand-tied in our signature soft pink wrap, this cheerful birthday bouquet pairs blush garden roses with pink gerberas and delicate alstroemeria. The perfect way to brighten someone's special day.",
    flowers:["Pink Garden Roses","Gerbera Daisies","Alstroemeria","Eucalyptus"], stock:12 },
  { id:"eternal-red-romance", name:"Eternal Red Romance", price:2299, old:2599, category:"anniversary", tag:"Premium",
    img:"assets/p-anniversary.jpg",
    short:"Two dozen long-stem red roses with baby's breath.",
    desc:"A timeless declaration of love—24 long-stem red roses arranged with airy baby's breath and lush greens, wrapped in luxe rose paper with a satin ribbon.",
    flowers:["Long-stem Red Roses","Baby's Breath","Italian Ruscus"], stock:8 },
  { id:"ivory-bridal-bouquet", name:"Ivory Bridal Bouquet", price:3499, category:"wedding", tag:"Bridal",
    img:"assets/p-wedding.jpg",
    short:"An elegant hand-tied bouquet of ivory roses & eucalyptus.",
    desc:"Crafted for your most precious moment—ivory garden roses, ranunculus and silver dollar eucalyptus tied with a flowing silk ribbon. Custom sizing available on request.",
    flowers:["Ivory Garden Roses","Ranunculus","Silver Dollar Eucalyptus","Italian Ruscus"], stock:5 },
  { id:"peaceful-white-lilies", name:"Peaceful White Lilies", price:1899, category:"sympathy",
    img:"assets/p-sympathy.jpg",
    short:"Serene white lilies and chrysanthemums.",
    desc:"A respectful, gentle arrangement of stargazer lilies and white chrysanthemums to express your deepest sympathies with grace and warmth.",
    flowers:["White Stargazer Lilies","White Chrysanthemums","Eucalyptus"], stock:10 },
  { id:"valentine-passion", name:"Valentine Passion Box", price:2799, old:3199, category:"valentine", tag:"Limited",
    img:"assets/p-valentine.jpg",
    short:"Heart-shaped box of premium red roses.",
    desc:"Say it without words. A heart-shaped arrangement of velvety red roses, finished with pink ribbon and a complimentary handwritten note.",
    flowers:["Premium Red Roses","Eucalyptus","Heart Box"], stock:7 },
  { id:"mothers-day-tulips", name:"Mother's Day Pastel Tulips", price:1699, category:"mothers",
    img:"assets/p-mothers.jpg",
    short:"Soft pink tulips, roses and lavender.",
    desc:"A loving tribute for mom—Dutch tulips, pastel roses and fragrant lavender wrapped in pearlescent pink paper.",
    flowers:["Dutch Tulips","Pastel Roses","Lavender","Limonium"], stock:9 },
  { id:"sunny-graduation", name:"Sunny Graduation Bouquet", price:1599, category:"graduation",
    img:"assets/p-graduation.jpg",
    short:"Cheerful sunflowers with money origami accents.",
    desc:"Celebrate the new graduate with bold sunflowers, white lilies and our signature money origami—an upgrade option available at checkout.",
    flowers:["Sunflowers","White Lilies","Greens"], stock:11 },
  { id:"pastel-rose-mix", name:"Pastel Rose Mix", price:1799, category:"birthday",
    img:"assets/p-mixed.jpg",
    short:"Soft pink, cream and lavender roses with limonium.",
    desc:"A dreamy mix of pastel roses with lavender accents, wrapped in soft lilac paper. A versatile gift for any happy occasion.",
    flowers:["Pink Roses","Cream Roses","Lavender Limonium","Eucalyptus"], stock:14 },
];

window.CATEGORIES = [
  { id:"birthday",  name:"Birthday Flowers",       ico:"🎂" },
  { id:"anniversary", name:"Anniversary Flowers",  ico:"💞" },
  { id:"wedding",   name:"Wedding Flowers",        ico:"💍" },
  { id:"sympathy",  name:"Sympathy Flowers",       ico:"🕊️" },
  { id:"valentine", name:"Valentine's Bouquets",   ico:"❤️" },
  { id:"mothers",   name:"Mother's Day Bouquets",  ico:"🌷" },
  { id:"graduation",name:"Graduation Bouquets",    ico:"🎓" },
];

window.SHOP = {
  name: "Flower Bouquet By: Ellyse",
  phone: "+63 956 650 4470",
  phoneRaw: "+639566504470",
  whatsapp: "639566504470",
  email: "hello@flowerbyellyse.ph",
  address: "Jones Avenue Fuente, Cebu City, Philippines, 5600",
  deliveryFee: 150,
  currency: "₱",
};
